### ISSUE TITLE
Exception: User is not logged in, make sure account has been activated

### ISSUE THREAD

**Issue by digitalw00t** [karl0ss/GoGoDownloader#15]
Seems the gogoanime site decided to start changing the actual web url now.  After verifything the usename/password is correct I get this:
Traceback (most recent call last):
  File "GoGoDownloader.py", line 176, in <module>
    gogodownloader(config)
  File "GoGoDownloader.py", line 141, in gogodownloader
    gogo.user_logged_in_check()
  File "/home/digitalw00t/GoGoDownloader/backend.py", line 130, in user_logged_in_check
    raise Exception(
Exception: User is not logged in, make sure account has been activated

**Comment by linuxlonestar** [comment]
Hey! try putting your email you used for signup in the config.json instead of your username. worked for me!
